version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  postgres:
    image: postgres:13.3
    container_name: "postgres"
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
  service-one:
    image: backend-service
    container_name: backend-service
    build: ./microservice_1
    volumes:
      - ../src:/opt/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  service-two:
    image: notification-service
    container_name: notification-service
    build: ./microservice_notification
    volumes:
      - ../src:/opt/app
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq