version: "3.9"

services:

  postgres:
    image: postgres:13.3
    container_name: "postgres"
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  service-one:
    image: backend-service
    container_name: backend-service
    build: ./
    volumes:
      - ../src:/opt/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres