version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  service-two:
    image: notification-service
    container_name: notification-service
    build: ./
    volumes:
      - ../src:/opt/app
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
