CREATE TABLE public.course
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT course_pkey PRIMARY KEY (id),
    CONSTRAINT uk_msgoex7rold2eqqf1cllhk02i UNIQUE (title)
)

GO
ALTER TABLE public.course
    OWNER to postgres;
GO