CREATE TABLE public.module
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    module_status character varying(255) COLLATE pg_catalog."default",
    "time" time without time zone,
    title character varying(255) COLLATE pg_catalog."default",
    student_id bigint,
    course_id bigint,
    mentor_id bigint,
    CONSTRAINT module_pkey PRIMARY KEY (id),
    CONSTRAINT fk29nxkq3vr8kbeexubf5dcm2tp FOREIGN KEY (mentor_id)
        REFERENCES public.mentor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkfq09oddpwjoxcirvkh9vnfnsg FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fknn8ppxtep17fjhdmammca5lie FOREIGN KEY (student_id)
        REFERENCES public.student (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
GO
ALTER TABLE public.module
    OWNER to postgres;
GO