CREATE TABLE public.student
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    surname character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    mentor_id bigint,
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT unique_student_username UNIQUE (username),
    CONSTRAINT fk_mentor_id FOREIGN KEY (mentor_id)
        REFERENCES public.mentor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
GO
ALTER TABLE public.student
    OWNER to postgres;
GO